# -*- coding: utf-8 -*-
"""assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zhER_a0Ph9wDQEFJyoFvg9W24czSg11S
"""




from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

import pandas as pd
import numpy as np
import patsy as pt

data = pd.read_csv("https://github.com/dustywhite7/Econ8310/raw/master/AssignmentData/assignment3.csv")
data.head()

# Commented out IPython magic to ensure Python compatibility.
model = DecisionTreeClassifier( max_depth = 10, min_samples_leaf = 10 )

Y, X = data["meal"], data.drop(["meal", "id", "DateTime"], axis=1)

x, xt, y, yt = train_test_split(X, Y, test_size=0.33, random_state=42)

modelFit = model.fit(x,y)

print("\n\nIn-sample accuracy: %s%%\n\n"
#  % str(round(100*accuracy_score(y, model.predict(x)), 2)))
print("\n\nOut-of-sample accuracy: %s%%\n\n"
# %str(round(100*accuracy_score(yt, model.predict(xt)), 2)))

test = pd.read_csv("https://github.com/dustywhite7/Econ8310/raw/master/AssignmentData/assignment3test.csv")
testNew = test.drop(["meal", "id", "DateTime"], axis=1)
testNew.head()

pred = modelFit.predict(testNew)

